#!/bin/bash
# --------------------------------------------------------------------------
# This script installs files and services specific to this project.
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/simple-radio
#
# --------------------------------------------------------------------------

# --- check user parameter   -----------------------------------------------

if [ -z "$1" ]; then
  echo -e "usage: $0 username LIRC-pin" >&2
  exit 3
else
  USERNAME="$1"
fi

if [ -z "$2" ]; then
  echo -e "usage: $0 username LIRC-pin" >&2
  exit 3
else
  LIRC_PIN="$2"
fi

# --- defaults used during installation   ----------------------------------

PACKAGES="python3-smbus mpg123 mp3info lirc"
PROJECT="simple-radio"

# --- basic packages   ------------------------------------------------------

if [ -n "$PACKAGES" ]; then
  apt-get update
  apt-get -y install $PACKAGES
fi

# --- install specific files   ----------------------------------------------

rand="$RANDOM"
if [ -f /etc/${PROJECT}.conf ]; then
  # save current configuration
  mv /etc/${PROJECT}.conf /etc/${PROJECT}.conf.$rand
fi

for f in `find $(dirname "$0")/../files/ -type f`; do
  cp "$f" "${f#*files}"
  chown root:root "${f#*files}"
done
chmod 755 /usr/local/bin/${PROJECT}.py
chmod 755 /usr/local/bin/show_charset.py
chmod 644 /etc/${PROJECT}.conf
chmod 644 /etc/systemd/system/${PROJECT}.service

# restore old configuration
if [ -f /etc/${PROJECT}.conf.$rand ]; then
  mv -f /etc/${PROJECT}.conf /etc/${PROJECT}.conf.new
  mv /etc/${PROJECT}.conf.$rand /etc/${PROJECT}.conf
  echo -e "\nnew version of configuration file: /etc/${PROJECT}.conf.new"
fi

# --- configure system for i2c   --------------------------------------------

restart=0

# update /boot/config.txt
if ! grep -q "^dtparam=i2c_arm=on" /boot/config.txt ; then
  echo -e "[INFO] configuring i2c in /boot/config.txt" 2>&1
  echo "dtparam=i2c_arm=on" >> /boot/config.txt
  restart=1
fi

if ! grep -q "^dtoverlay=lirc-rpi" /boot/config.txt ; then
  echo -e "[INFO] configuring LIRC in /boot/config.txt" 2>&1
  echo "dtoverlay=lirc-rpi,gpio_in_pin=$LIRC_PIN" >> /boot/config.txt
  restart=1
fi

# update /etc/modules
if ! grep -q "^i2c-dev" /etc/modules; then
  echo -e "[INFO] configuring /etc/modules" 2>&1
  echo "i2c-dev" >> /etc/modules
  restart=1
fi

# --- fix user of service   -------------------------------------------------

sed -i -e "/User=/s/=.*/=$USERNAME/" /etc/systemd/system/${PROJECT}.service
usermod -a -G i2c,audio "$USERNAME"

# --- copy channel file   ---------------------------------------------------

if [ ! -f "/home/$USERNAME/simple-radio.channels" ]; then
  cp $(dirname "$0")/../examples/simple-radio.channels "/home/$USERNAME/simple-radio.channels"
  chown "$USERNAME" "/home/$USERNAME/simple-radio.channels"
fi

# --- activate service   ----------------------------------------------------

systemctl enable ${PROJECT}.service

# --- final configuration is manual   ---------------------------------------

echo -e "\nPlease edit /etc/${PROJECT}.conf and start ${PROJECT}.service"
if [ $restart -eq 1 ]; then
  echo -e "\n### Reboot required. Please reboot the system! ###"
fi
