#!/bin/bash
# -----------------------------------------------------------------------------
# Compile and install libcec including python-wrapper.
# This script is a modified version of the script in the libcec-source taken
# from libcec/docs/README.raspberrypi.md
#
#libCEC(R) is Copyright (C) 2011-2015 Pulse-Eight Limited.  All rights reserved.
#libCEC(R) is a original work, containing original code.
#
#libCEC(R) is a trademark of Pulse-Eight Limited.
#
# License: GPL2 (original libcec-license)
#
# Website: https://github.com/bablokb/simple-radio
#
# -----------------------------------------------------------------------------

# install necessary packages
sudo apt-get update
sudo apt-get -y install git cmake libudev-dev libxrandr-dev python-dev swig

# install platform-base
cd
git clone https://github.com/Pulse-Eight/platform.git
mkdir platform/build
cd platform/build
cmake ..
make
sudo make install

# install libcec for Python2.7. Remove the lines starting with -DPYTHON...
# to compile and install für Python3
cd
git clone https://github.com/Pulse-Eight/libcec.git

mkdir libcec/build
cd libcec/build
cmake -DRPI_INCLUDE_DIR=/opt/vc/include -DRPI_LIB_DIR=/opt/vc/lib \
      -DPYTHON_LIBRARY=/usr/lib/arm-linux-gnueabihf/libpython2.7.so.1.0 \
      -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 \
      ..

# choose one of the following lines depending on the number of your CPUs
#make -j4
make
sudo make install
sudo ldconfig
